[package]
name = "cpu_benchmark_tool"
version = "0.1.0"
edition = "2021"
description = "Tool to test your CPU"

[dependencies]
sysinfo = "0.29"
indicatif = "0.17"
colored = "2.1"

[profile.release]
lto = "fat"
strip = "debuginfo"